# Generated by Django 4.1.2 on 2022-12-11 17:20

import apps.core.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseFormModel',
            fields=[
                ('created', apps.core.models.DTFieldCustom(auto_now_add=True)),
                ('modified', apps.core.models.DTFieldCustom(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='New form', max_length=30, verbose_name='')),
                ('author', models.CharField(max_length=30)),
                ('description', models.CharField(default='Description', max_length=100, verbose_name='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BaseFieldModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', apps.core.models.DTFieldCustom(auto_now_add=True)),
                ('modified', apps.core.models.DTFieldCustom(auto_now=True)),
                ('author', models.CharField(default='unknown', max_length=30)),
                ('name', models.CharField(max_length=30, verbose_name='')),
                ('type', models.CharField(choices=[('CharField', 'Text (string)'), ('TextArea', 'Text (paragraph)'), ('Choice', 'One from list')], default='CharField', max_length=16, verbose_name='')),
                ('customform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customform.baseformmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BaseAnswerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', apps.core.models.DTFieldCustom(auto_now_add=True)),
                ('modified', apps.core.models.DTFieldCustom(auto_now=True)),
                ('author', models.CharField(default='unknown', max_length=30)),
                ('answer', models.CharField(max_length=50, verbose_name='')),
                ('customfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customform.basefieldmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
